<a href="https://colab.research.google.com/github/banno-0720/learning_PyTorch/blob/main/1_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
TENSOR2 = torch.tensor(([[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]]))
TENSOR2

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [18]:
TENSOR2.shape
# No idea why it is (5, 1, 3, 3) and not (1, 5, 3, 3)

torch.Size([5, 1, 3, 3])

In [19]:
TENSOR2.ndim

4

In [20]:
TENSOR3 = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]]])

TENSOR3 = TENSOR3.unsqueeze(0)  # Add a batch dimension
TENSOR3

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [21]:
TENSOR3.shape

torch.Size([1, 5, 3, 3])

In [22]:
TENSOR3.ndim

4

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [23]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3889, 0.9458, 0.4648, 0.6747],
        [0.8148, 0.7269, 0.4762, 0.8707],
        [0.8843, 0.3232, 0.3382, 0.7767]])

In [24]:
random_tensor.ndim

2

In [25]:
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [26]:
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeroes*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [30]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
torch.__version__

'2.4.0+cu121'

In [32]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big issues you will run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [33]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # What datatype is the tensor(ex. float32 or float16)(used with tensor.float16)
                               device=None, # What device is your tensor on? Can use "cpu" or "cuda".
                               requires_grad=False) # whether or not to track gradients with this tensors operation
float_32_tensor # torch.float also works

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16) # torch.half also works
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_64_tensor = float_32_tensor.type(torch.float64) # torch.double also works
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [37]:
float_16_2_tensor = float_32_tensor.type(torch.bfloat16)
float_16_2_tensor

tensor([3., 6., 9.], dtype=torch.bfloat16)

In [38]:
integer_32_tensor = torch.tensor([3,6,9],
                               dtype=torch.int32, # torch.int also works
                               device=None,
                               requires_grad=False)
integer_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [39]:
integer_64_tensor = float_32_tensor.type(torch.int64) #torch.long also works
integer_64_tensor

tensor([3, 6, 9])

In [40]:
complex_32_tensor = float_32_tensor.type(torch.complex32) # torch.chalf also works
complex_32_tensor

<ipython-input-40-f81a4542917a>:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at ../aten/src/ATen/EmptyTensor.cpp:44.)
  complex_32_tensor = float_32_tensor.type(torch.complex32) # torch.chalf also works


tensor([3.+0.j, 6.+0.j, 9.+0.j], dtype=torch.complex32)

In [41]:
complex_64_tensor = float_32_tensor.type(torch.complex64) # torch.cfloat also works
complex_64_tensor

tensor([3.+0.j, 6.+0.j, 9.+0.j])

### Multiplication tests

In [42]:
float_16_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [43]:
float_16_tensor * float_64_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [44]:
float_16_tensor * float_32_tensor # I learnt if it is the default datatype it doesnt mention it then in multiplication like it did in others

tensor([ 9., 36., 81.])

In [45]:
float_16_tensor * float_16_2_tensor # Why is there even type 2 float 16? (watch https://youtu.be/7q1Gh1KOlzw maybe this will help)

tensor([ 9., 36., 81.])

In [46]:
float_16_tensor * integer_64_tensor # I dont know why it picked up float16 and not int64

tensor([ 9., 36., 81.], dtype=torch.float16)

In [47]:
float_16_tensor * complex_64_tensor # Was totally not expecting this to run

tensor([ 9.+0.j, 36.+0.j, 81.+0.j])

In [48]:
float_16_tensor * complex_32_tensor # for complex, complex64 is default so thats why it didnt mention dtype before

tensor([ 9.+0.j, 36.+0.j, 81.+0.j], dtype=torch.complex32)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [49]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6995, 0.2174, 0.9311, 0.9321],
        [0.3849, 0.5961, 0.7217, 0.0685],
        [0.1061, 0.2195, 0.1989, 0.3375]])

In [50]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6995, 0.2174, 0.9311, 0.9321],
        [0.3849, 0.5961, 0.7217, 0.0685],
        [0.1061, 0.2195, 0.1989, 0.3375]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [51]:
tensor = torch.tensor([1,2,3])
tensor + 20

tensor([21, 22, 23])

In [52]:
tensor * 10

tensor([10, 20, 30])

In [53]:
tensor - 10

tensor([-9, -8, -7])

In [54]:
torch.mul(tensor,20)

tensor([20, 40, 60])

In [55]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [56]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [57]:
torch.matmul(tensor,tensor)

tensor(14)

In [58]:
tensor @ tensor

tensor(14)

In [59]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.84 ms, sys: 129 µs, total: 1.96 ms
Wall time: 2.98 ms


In [60]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.4 ms, sys: 63 µs, total: 1.47 ms
Wall time: 1.38 ms


tensor(14)

### One of the most common errors in deep learning: shape errors

In [61]:
# this wont run due to error
# torch.matmul(torch.rand(3,2),torch.rand(3,2))

In [62]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[1.3749, 0.7504],
        [1.7354, 0.9601]])

In [63]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.6914, 0.3383, 0.5919],
        [0.6289, 0.3473, 0.4455],
        [0.6968, 0.5081, 0.2044]])

In [64]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.mm(tensor_A,tensor_B) # torch.mm is the same as torch.matmul (it's an alias for matmul)

In [65]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [66]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [67]:
# The matrix multiplication operation works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [68]:
torch.matmul(tensor_A.T,tensor_B)

tensor([[ 76, 103],
        [100, 136]])

### Finding the min,max,mean,sum,etc(tensor aggregation)

In [69]:
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [70]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [71]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [72]:
# note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [73]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [74]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [75]:
x.argmin() # returns index position of target tensor where the minimum value occurs

tensor(0)

In [76]:
x[0]

tensor(1)

In [77]:
x.argmax() # returns index position of target tensor where the maximum value occurs

tensor(9)

In [78]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing & Permute tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [79]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [80]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [81]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [82]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [87]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [92]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [93]:
print(f"previous tensor: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [89]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [90]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [91]:
x_reshaped.squeeze().shape

torch.Size([9])

In [97]:
x_original = torch.rand(size=(224,224,3)) # [height,width,colour_channels]

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
