<a href="https://colab.research.google.com/github/banno-0720/learning_PyTorch/blob/main/1_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [18]:
TENSOR2 = torch.tensor(([[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]]))
TENSOR2

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [19]:
TENSOR2.shape
# No idea why it is (5, 1, 3, 3) and not (1, 5, 3, 3)

torch.Size([5, 1, 3, 3])

In [20]:
TENSOR2.ndim

4

In [21]:
TENSOR3 = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]]])

TENSOR3 = TENSOR3.unsqueeze(0)  # Add a batch dimension
TENSOR3

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [22]:
TENSOR3.shape

torch.Size([1, 5, 3, 3])

In [23]:
TENSOR3.ndim

4

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [24]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5541, 0.1122, 0.9733, 0.7410],
        [0.9958, 0.2526, 0.5020, 0.1642],
        [0.2659, 0.6086, 0.0706, 0.6979]])

In [25]:
random_tensor.ndim

2

In [26]:
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [27]:
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
zeroes*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [31]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
torch.__version__

'2.4.0+cu121'

In [33]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big issues you will run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [34]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # What datatype is the tensor(ex. float32 or float16)(used with tensor.float16)
                               device=None, # What device is your tensor on? Can use "cpu" or "cuda".
                               requires_grad=False) # whether or not to track gradients with this tensors operation
float_32_tensor # torch.float also works

tensor([3., 6., 9.])

In [35]:
float_32_tensor.dtype

torch.float32

In [36]:
float_16_tensor = float_32_tensor.type(torch.float16) # torch.half also works
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_64_tensor = float_32_tensor.type(torch.float64) # torch.double also works
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [38]:
float_16_2_tensor = float_32_tensor.type(torch.bfloat16)
float_16_2_tensor

tensor([3., 6., 9.], dtype=torch.bfloat16)

In [39]:
integer_32_tensor = torch.tensor([3,6,9],
                               dtype=torch.int32, # torch.int also works
                               device=None,
                               requires_grad=False)
integer_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [40]:
integer_64_tensor = float_32_tensor.type(torch.int64) #torch.long also works
integer_64_tensor

tensor([3, 6, 9])

In [41]:
complex_32_tensor = float_32_tensor.type(torch.complex32) # torch.chalf also works
complex_32_tensor

<ipython-input-41-f81a4542917a>:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at ../aten/src/ATen/EmptyTensor.cpp:44.)
  complex_32_tensor = float_32_tensor.type(torch.complex32) # torch.chalf also works


tensor([3.+0.j, 6.+0.j, 9.+0.j], dtype=torch.complex32)

In [42]:
complex_64_tensor = float_32_tensor.type(torch.complex64) # torch.cfloat also works
complex_64_tensor

tensor([3.+0.j, 6.+0.j, 9.+0.j])

### Multiplication tests

In [43]:
float_16_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [44]:
float_16_tensor * float_64_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [45]:
float_16_tensor * float_32_tensor # I learnt if it is the default datatype it doesnt mention it then in multiplication like it did in others

tensor([ 9., 36., 81.])

In [46]:
float_16_tensor * float_16_2_tensor # Why is there even type 2 float 16? (watch https://youtu.be/7q1Gh1KOlzw maybe this will help)

tensor([ 9., 36., 81.])

In [47]:
float_16_tensor * integer_64_tensor # I dont know why it picked up float16 and not int64

tensor([ 9., 36., 81.], dtype=torch.float16)

In [48]:
float_16_tensor * complex_64_tensor # Was totally not expecting this to run

tensor([ 9.+0.j, 36.+0.j, 81.+0.j])

In [49]:
float_16_tensor * complex_32_tensor # for complex, complex64 is default so thats why it didnt mention dtype before

tensor([ 9.+0.j, 36.+0.j, 81.+0.j], dtype=torch.complex32)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [50]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8726, 0.2078, 0.4128, 0.8001],
        [0.1171, 0.5915, 0.8072, 0.3554],
        [0.1132, 0.1408, 0.2781, 0.4488]])

In [51]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8726, 0.2078, 0.4128, 0.8001],
        [0.1171, 0.5915, 0.8072, 0.3554],
        [0.1132, 0.1408, 0.2781, 0.4488]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [52]:
tensor = torch.tensor([1,2,3])
tensor + 20

tensor([21, 22, 23])

In [53]:
tensor * 10

tensor([10, 20, 30])

In [54]:
tensor - 10

tensor([-9, -8, -7])

In [55]:
torch.mul(tensor,20)

tensor([20, 40, 60])

In [56]:
torch.add(tensor,10)

tensor([11, 12, 13])