<a href="https://colab.research.google.com/github/banno-0720/learning_PyTorch/blob/main/1_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Tue Sep 10 14:04:22 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
TENSOR2 = torch.tensor(([[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]]))
TENSOR2

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [18]:
TENSOR2.shape
# No idea why it is (5, 1, 3, 3) and not (1, 5, 3, 3)

torch.Size([5, 1, 3, 3])

In [19]:
TENSOR2.ndim

4

In [20]:
TENSOR3 = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]]])

TENSOR3 = TENSOR3.unsqueeze(0)  # Add a batch dimension
TENSOR3

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [21]:
TENSOR3.shape

torch.Size([1, 5, 3, 3])

In [22]:
TENSOR3.ndim

4

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [23]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0526, 0.7176, 0.0830, 0.4602],
        [0.1106, 0.2487, 0.0047, 0.9165],
        [0.2891, 0.0041, 0.1142, 0.4853]])

In [24]:
random_tensor.ndim

2

In [25]:
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [26]:
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeroes*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [30]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
torch.__version__

'2.4.0+cu121'

In [32]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big issues you will run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [33]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # What datatype is the tensor(ex. float32 or float16)(used with tensor.float16)
                               device=None, # What device is your tensor on? Can use "cpu" or "cuda".
                               requires_grad=False) # whether or not to track gradients with this tensors operation
float_32_tensor # torch.float also works

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16) # torch.half also works
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_64_tensor = float_32_tensor.type(torch.float64) # torch.double also works
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [37]:
float_16_2_tensor = float_32_tensor.type(torch.bfloat16)
float_16_2_tensor

tensor([3., 6., 9.], dtype=torch.bfloat16)

In [38]:
integer_32_tensor = torch.tensor([3,6,9],
                               dtype=torch.int32, # torch.int also works
                               device=None,
                               requires_grad=False)
integer_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [39]:
integer_64_tensor = float_32_tensor.type(torch.int64) #torch.long also works
integer_64_tensor

tensor([3, 6, 9])

In [40]:
complex_32_tensor = float_32_tensor.type(torch.complex32) # torch.chalf also works
complex_32_tensor

<ipython-input-40-f81a4542917a>:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at ../aten/src/ATen/EmptyTensor.cpp:44.)
  complex_32_tensor = float_32_tensor.type(torch.complex32) # torch.chalf also works


tensor([3.+0.j, 6.+0.j, 9.+0.j], dtype=torch.complex32)

In [41]:
complex_64_tensor = float_32_tensor.type(torch.complex64) # torch.cfloat also works
complex_64_tensor

tensor([3.+0.j, 6.+0.j, 9.+0.j])

### Multiplication tests

In [42]:
float_16_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [43]:
float_16_tensor * float_64_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [44]:
float_16_tensor * float_32_tensor # I learnt if it is the default datatype it doesnt mention it then in multiplication like it did in others

tensor([ 9., 36., 81.])

In [45]:
float_16_tensor * float_16_2_tensor # Why is there even type 2 float 16? (watch https://youtu.be/7q1Gh1KOlzw maybe this will help)

tensor([ 9., 36., 81.])

In [46]:
float_16_tensor * integer_64_tensor # I dont know why it picked up float16 and not int64

tensor([ 9., 36., 81.], dtype=torch.float16)

In [47]:
float_16_tensor * complex_64_tensor # Was totally not expecting this to run

tensor([ 9.+0.j, 36.+0.j, 81.+0.j])

In [48]:
float_16_tensor * complex_32_tensor # for complex, complex64 is default so thats why it didnt mention dtype before

tensor([ 9.+0.j, 36.+0.j, 81.+0.j], dtype=torch.complex32)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [49]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2641, 0.9292, 0.2515, 0.2797],
        [0.5464, 0.9062, 0.4888, 0.5044],
        [0.9274, 0.0824, 0.6707, 0.6015]])

In [50]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2641, 0.9292, 0.2515, 0.2797],
        [0.5464, 0.9062, 0.4888, 0.5044],
        [0.9274, 0.0824, 0.6707, 0.6015]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [51]:
tensor = torch.tensor([1,2,3])
tensor + 20

tensor([21, 22, 23])

In [52]:
tensor * 10

tensor([10, 20, 30])

In [53]:
tensor - 10

tensor([-9, -8, -7])

In [54]:
torch.mul(tensor,20)

tensor([20, 40, 60])

In [55]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [56]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [57]:
torch.matmul(tensor,tensor)

tensor(14)

In [58]:
tensor @ tensor

tensor(14)

In [59]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.39 ms, sys: 68 µs, total: 1.46 ms
Wall time: 1.67 ms


In [60]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.1 ms, sys: 185 µs, total: 1.29 ms
Wall time: 3.15 ms


tensor(14)

### One of the most common errors in deep learning: shape errors

In [61]:
# this wont run due to error
# torch.matmul(torch.rand(3,2),torch.rand(3,2))

In [62]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.7053, 0.7827],
        [0.4913, 0.6952]])

In [63]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.8730, 0.4483, 0.8239],
        [1.4683, 0.9311, 1.3472],
        [0.3310, 0.1296, 0.3212]])

In [64]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.mm(tensor_A,tensor_B) # torch.mm is the same as torch.matmul (it's an alias for matmul)

In [65]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [66]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [67]:
# The matrix multiplication operation works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [68]:
torch.matmul(tensor_A.T,tensor_B)

tensor([[ 76, 103],
        [100, 136]])

### Finding the min,max,mean,sum,etc(tensor aggregation)

In [69]:
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [70]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [71]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [72]:
# note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [73]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [74]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [75]:
x.argmin() # returns index position of target tensor where the minimum value occurs

tensor(0)

In [76]:
x[0]

tensor(1)

In [77]:
x.argmax() # returns index position of target tensor where the maximum value occurs

tensor(9)

In [78]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing & Permute tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [79]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [80]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [81]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [82]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [83]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [84]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [85]:
print(f"previous tensor: {x_squeezed}")
print(f"previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [86]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [87]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [88]:
x_reshaped.squeeze().shape

torch.Size([9])

In [89]:
x_original = torch.rand(size=(224,224,3)) # [height,width,colour_channels]

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (select data from tensors)
Indexing with PyTorch is similar to indexing with Numpy

In [90]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [91]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [92]:
x[0][0] # or x[0,0]

tensor([1, 2, 3])

In [93]:
x[:, 0]

tensor([[1, 2, 3]])

In [94]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [95]:
x[0, 0, :]

tensor([1, 2, 3])

In [96]:
print(x[0,2,2])
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


### PyTorch tensors & Numpy

Numpy is a popular scientific Python numerical computing library.
PyTorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [97]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [98]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [99]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [100]:
# Change the value of array, what will this do to 'tensor'? (basically does it act like view)
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [101]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [102]:
numpy_tensor.dtype

dtype('float32')

In [103]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness

In [104]:
torch.rand(3, 3)

tensor([[0.0413, 0.8914, 0.4366],
        [0.3152, 0.7360, 0.1129],
        [0.3170, 0.0270, 0.2020]])

In [105]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5367, 0.9293, 0.7080, 0.2843],
        [0.2813, 0.4132, 0.3768, 0.8171],
        [0.4075, 0.3414, 0.2481, 0.0463]])
tensor([[0.3981, 0.1390, 0.3695, 0.5336],
        [0.3093, 0.6204, 0.7332, 0.9636],
        [0.8672, 0.0199, 0.9709, 0.6692]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [106]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

### Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory(good).

## 1. Getting a GPU

1. Easiest - use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options... , see this post for what option to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [107]:
!nvidia-smi

Tue Sep 10 14:04:33 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## 2. Check for GPU access with PyTorch

In [108]:
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

e.g. run on GPU if available,else default to CPU

In [109]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [110]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [111]:
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [112]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## 4. Moving tensors back to the CPU

In [113]:
# If tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy()


# TypeError                                 Traceback (most recent call last)
# <ipython-input-115-b7da913938a5> in <cell line: 2>()
#       1 # If tensor is on GPU, can't transform it to NumPy
# ----> 2 tensor_on_gpu.numpy()

# TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [114]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises

See exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [115]:
# problem 2
torch.manual_seed(42)
tensor1 = torch.rand(7, 7)
tensor1

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])

In [116]:
# problem 3
torch.manual_seed(42)
tensor2 = torch.rand(1,7)
tensor2

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566]])

In [117]:
torch.matmul(tensor1, tensor2.T)

tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])

In [118]:
# problem 4
torch.manual_seed(0)
tensor1 = torch.rand(7, 7)
torch.manual_seed(0)
tensor2 = torch.rand(1, 7)
torch.matmul(tensor1, tensor2.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [119]:
# problem 5
torch.cuda.manual_seed(1234)

In [120]:
# probem 6

# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [124]:
# problem 7
answer = torch.matmul(tensor_A, tensor_B.T)
answer, answer.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [127]:
# problem 8
max_value = torch.max(answer)
min_value = torch.min(answer)
max_value, min_value

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [128]:
# problem 9
arg_max = torch.argmax(answer)
arg_min = torch.argmin(answer)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [129]:
# problem 10

torch.manual_seed(7)
tensor_D = torch.rand(1,1,1,10)
tensor_E = tensor_D.squeeze()

print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
