<a href="https://colab.research.google.com/github/banno-0720/learning_PyTorch/blob/main/1_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
TENSOR2 = torch.tensor(([[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]],[[[1,2,3],[3,6,9],[2,4,5]]]))
TENSOR2

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]],


        [[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [20]:
TENSOR2.shape
# No idea why it is (5, 1, 3, 3) and not (1, 5, 3, 3)

torch.Size([5, 1, 3, 3])

In [21]:
TENSOR2.ndim

4

In [23]:
TENSOR3 = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                        [[1, 2, 3], [3, 6, 9], [2, 4, 5]]])

TENSOR3 = TENSOR3.unsqueeze(0)  # Add a batch dimension
TENSOR3

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [24]:
TENSOR3.shape

torch.Size([1, 5, 3, 3])

In [25]:
TENSOR3.ndim

4

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [26]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6068, 0.8801, 0.2727, 0.4537],
        [0.8690, 0.5453, 0.1539, 0.6497],
        [0.6412, 0.4742, 0.4479, 0.7695]])

In [30]:
random_tensor.ndim

2

In [31]:
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and ones

In [32]:
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
zeroes*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [40]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
torch.__version__

'2.4.0+cu121'

In [42]:
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])